// <auto-generated />
using CSharpAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSharpAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240110232256_updateModelBuilder")]
    partial class updateModelBuilder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CSharpAPI.Models.Destiny", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("city");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("imageUrls");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.ToTable("destiny");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Lençois",
                            Description = "Com uma bela queda d’água em meio a grandiosos paredões rochosos, a Cachoeira do Mosquito impressiona pela sua beleza e graciosidade natural.",
                            ImageUrls = "[\"https://github.com/rodrigo-alberto/goodVacation-CSharpAPI/assets/85527665/e21efdfa-1b3e-4ad7-ac47-561e304f33c4\",\"https://github.com/rodrigo-alberto/goodVacation-CSharpAPI/assets/85527665/18274ddb-11b5-4c65-a006-dee24aa1e78f\"]",
                            Name = "Cachoeira do Mosquito",
                            State = "Bahia"
                        },
                        new
                        {
                            Id = 2,
                            City = "Angra dos Reis",
                            Description = "Um sítio histórico e natural com mais de 100 praias, além de cachoeiras, rios, trilhas, construções históricas e uma rica flora e fauna.",
                            ImageUrls = "[\"https://github.com/rodrigo-alberto/goodVacation-CSharpAPI/assets/85527665/0fe9f6d6-a3ab-4691-bda6-94bddfd922f7\",\"https://github.com/rodrigo-alberto/goodVacation-CSharpAPI/assets/85527665/5a2b541d-4d6c-4fff-9725-9f85f22cadfe\"]",
                            Name = "Ilha Grande",
                            State = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = 3,
                            City = "Aracaju",
                            Description = "Aracaju é um destino que reúne um extenso litoral, praias de rio, centro histórico repleto de museus e mercados públicos, além de uma culinária deliciosa.",
                            ImageUrls = "[\"https://github.com/rodrigo-alberto/goodVacation-CSharpAPI/assets/85527665/d89a7598-da08-4fe4-802c-d45b60f9f8be\",\"https://github.com/rodrigo-alberto/goodVacation-CSharpAPI/assets/85527665/70027f1a-ca8f-410f-bbfd-3840caa805a8\"]",
                            Name = "Praia de Atalaia",
                            State = "Sergipe"
                        },
                        new
                        {
                            Id = 4,
                            City = "Iraquara",
                            Description = "As águas cristalinas do rio Pratinha são um convite para uma pedalada em família, um teste de equilíbrio ou remo em meio à natureza.",
                            ImageUrls = "[\"https://github.com/rodrigo-alberto/goodVacation-CSharpAPI/assets/85527665/3bdddeb1-7f26-4897-b62c-aafbe38f136c\",\"https://github.com/rodrigo-alberto/goodVacation-CSharpAPI/assets/85527665/c50c9cc7-d752-4705-981f-33f27359a9bc\"]",
                            Name = "Pratinha",
                            State = "Bahia"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
